# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('drive-recorder', ['core', 'internet', 'mobility', 'wifi', "netanim"])
    module.source = [
        'model/drive-recorder-util.cc',
        'model/drive-recorder-cli-app.cc',
        'helper/drive-recorder-cli-helper.cc',
        'model/drive-recorder-ser-app.cc',
        'helper/drive-recorder-ser-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('drive-recorder')
    module_test.source = [
        'test/drive-recorder-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'drive-recorder'
    headers.source = [
        'model/drive-recorder-util.h',
        'model/drive-recorder-cli-app.h',
        'helper/drive-recorder-cli-helper.h',
        'model/drive-recorder-ser-app.h',
        'helper/drive-recorder-ser-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

